// Code generated by the nilness position fixture generator; DO NOT EDIT.

package nilness

import "k8s.io/klog/v2"

// Both calls must remain on one physical line to exercise token offsets.
func adversarialSameLineGenerated(p *NamespacedName) {
	klog.InfoS("safe", "p", &NamespacedName{}); klog.InfoS("unsafe", "p", p) // want `logging value may panic when nil`
}
